In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
#recenice
recenice = [ "the glass of milk",
            "the glass of juice",
            "the cup of tea",
            "I am a good boy",
            "I am a good developer",
            "understand the meaning of words",
            "your videos are good" 
    ]

In [8]:
#definisanje obima rijecnika
obim_rijeci = 10000

In [10]:
#Jedna Vruca Reprezentacija - One Hot Representation
jedna_vruca_repr = [one_hot(rijeci,obim_rijeci) for rijeci in recenice]
jedna_vruca_repr

[[6678, 3109, 4641, 7318],
 [6678, 3109, 4641, 6222],
 [6678, 3602, 4641, 6725],
 [8862, 3686, 5460, 3101, 8526],
 [8862, 3686, 5460, 3101, 3652],
 [5938, 6678, 7000, 4641, 499],
 [7787, 1857, 9177, 3101]]

In [14]:
#Reprezentacija Oznacavanja Rijeci - Word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [15]:
import numpy as np

In [23]:
#Ovdje je princip da sve recenice postanu ravnopravne kako bi bile prikladne za treniranje u RNN model, tako što se odredi
#duzina za sve recenice, te se vrsi popuna recenica nulama, tako da postanu identicne duzine...
#parametar padding, sa argumentom "pre" stavlja nule na pocetak, a sa "post" na kraj recenica.
duzina_recenice = 8
oznaceni_dokumenti = pad_sequences(jedna_vruca_repr, padding="pre",maxlen=duzina_recenice)
oznaceni_dokumenti

array([[   0,    0,    0,    0, 6678, 3109, 4641, 7318],
       [   0,    0,    0,    0, 6678, 3109, 4641, 6222],
       [   0,    0,    0,    0, 6678, 3602, 4641, 6725],
       [   0,    0,    0, 8862, 3686, 5460, 3101, 8526],
       [   0,    0,    0, 8862, 3686, 5460, 3101, 3652],
       [   0,    0,    0, 5938, 6678, 7000, 4641,  499],
       [   0,    0,    0,    0, 7787, 1857, 9177, 3101]])

In [27]:
#Reprezentacija Osobina
dimenzija = 10


In [29]:
#Stvaranje Modlea sa Slojem za oznacavanje
model = Sequential()

#dodavanje tog Embedding sloja modelu
model.add(Embedding(obim_rijeci,dimenzija,input_length=duzina_recenice))

#Sacinjavanje modela -"mse" jeste funkcija gubitka, dok "adam" je optimizer
model.compile("adam","mse")

In [32]:
#PREGLED modela
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.predict(oznaceni_dokumenti)

1/1 [==============================] - 3s 3s/step


array([[[-9.9880584e-03, -2.4734009e-02,  2.3397516e-02, -4.6144377e-02,
          1.5052680e-02,  3.5221908e-02,  1.0122310e-02,  7.4034445e-03,
          6.7297593e-03, -1.7066550e-02],
        [-9.9880584e-03, -2.4734009e-02,  2.3397516e-02, -4.6144377e-02,
          1.5052680e-02,  3.5221908e-02,  1.0122310e-02,  7.4034445e-03,
          6.7297593e-03, -1.7066550e-02],
        [-9.9880584e-03, -2.4734009e-02,  2.3397516e-02, -4.6144377e-02,
          1.5052680e-02,  3.5221908e-02,  1.0122310e-02,  7.4034445e-03,
          6.7297593e-03, -1.7066550e-02],
        [-9.9880584e-03, -2.4734009e-02,  2.3397516e-02, -4.6144377e-02,
          1.5052680e-02,  3.5221908e-02,  1.0122310e-02,  7.4034445e-03,
          6.7297593e-03, -1.7066550e-02],
        [-4.2716958e-02, -7.9453960e-03,  1.8512931e-02,  4.5243267e-02,
         -2.7561832e-02,  2.0832334e-02,  1.4377125e-03,  4.6240781e-02,
          2.6776839e-02,  2.7567148e-04],
        [ 3.6344532e-02,  1.7316911e-02, -2.0602454e-02,  1.

In [34]:
oznaceni_dokumenti[1]

array([   0,    0,    0,    0, 6678, 3109, 4641, 6222])

In [37]:
model.predict(oznaceni_dokumenti[0])

1/1 [==============================] - 8s 8s/step


array([[-0.00998806, -0.02473401,  0.02339752, -0.04614438,  0.01505268,
         0.03522191,  0.01012231,  0.00740344,  0.00672976, -0.01706655],
       [-0.00998806, -0.02473401,  0.02339752, -0.04614438,  0.01505268,
         0.03522191,  0.01012231,  0.00740344,  0.00672976, -0.01706655],
       [-0.00998806, -0.02473401,  0.02339752, -0.04614438,  0.01505268,
         0.03522191,  0.01012231,  0.00740344,  0.00672976, -0.01706655],
       [-0.00998806, -0.02473401,  0.02339752, -0.04614438,  0.01505268,
         0.03522191,  0.01012231,  0.00740344,  0.00672976, -0.01706655],
       [-0.04271696, -0.0079454 ,  0.01851293,  0.04524327, -0.02756183,
         0.02083233,  0.00143771,  0.04624078,  0.02677684,  0.00027567],
       [ 0.03634453,  0.01731691, -0.02060245,  0.01038934,  0.02699034,
         0.01859153, -0.02327398,  0.04824198, -0.0493697 ,  0.0494833 ],
       [-0.00270269,  0.02306228, -0.02570963,  0.00673039, -0.02729672,
        -0.01527879, -0.01683347,  0.01831556